name: CI
on:
  push:
  pull_request:
    branches: [ master, main ]
jobs:
  build-java:
    name: Build Java
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository and Submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build
        uses: gradle/gradle-build-action@v2.10.0
        with:
          arguments: build
